stages:
  - test

test:
  stage: test
  script:
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  # Install the dependencies for pyenv (defined here: https://github.com/pyenv/pyenv/wiki/Common-build-problems)
  - apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python-openssl
  - pip install tox
  # Install the package
  - pip install -r test-requirements.txt
  # Run tox which runs the unit & integration tests
  - tox
  artifacts:
      paths:
        - py27_log.html
      expire_in: 1 week
      when: on_failure